Install Viper and Z3 without sudo on Travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,12 +1,22 @@
 language: rust
 dist: trusty
-sudo: true
+sudo: false
 
 rust:
   - nightly
 
 jdk:
   - oraclejdk8
+
+# Add Viper's PPA and install Viper
+addons:
+  apt:
+    sources:
+      - sourceline: 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /'
+        key_url: 'http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc'
+    update: true
+    packages:
+      - viper
 
 cache:
   cargo: true
@@ -16,17 +26,19 @@ cache:
 
 env:
   global:
+    - USR_LOCAL=$HOME/local
     # Required to call the JVM
     - JAVA_HOME=/usr/lib/jvm/java-8-oracle
     - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
     # Required to run Viper on Ubuntu Trusty
-    - Z3_PATH=/usr/bin/z3
+    - Z3_PATH=$USR_LOCAL/bin/z3
 
 before_install:
-  # Add Viper's PPA
-  - wget -q -O - http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc | sudo apt-key add -
-  - echo 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /' | sudo tee /etc/apt/sources.list.d/viper.list
-  - travis_retry sudo apt-get update
+  # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
+  # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
+  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
+  # Prepare directory for local installations
+  - mkdir -p $USR_LOCAL
   # Download and compile Z3 with a known-to-work version
   - if [ ! -d .cache/z3 ]; then
       echo "Building Z3 from scratch";
@@ -35,7 +47,7 @@ before_install:
       rm z3.zip;
       mv z3-3865c453827506fc5c9d6c6c7c3d66d17030f158 tmp-z3;
       cd tmp-z3;
-      ./configure;
+      ./configure --prefix=$USR_LOCAL;
       cd build;
       make -j 2;
       cd ../..;
@@ -46,13 +58,12 @@ before_install:
     fi
 
 install:
-  - travis_retry sudo apt-get install viper
   - ( cd .cache/z3/build; sudo make install )
   - cargo install --force clippy rustfmt-nightly
 
 script:
-  - cargo fmt -- --write-mode=diff
   - cargo build
   - cargo test --verbose -- --nocapture
   - cargo clean
-  - cargo clippy
+  - cargo fmt -- --write-mode=diff || true
+  - cargo clippy || true
