Improve robustness of docker/prusti script, update Readme

diff --git a/docker/prusti b/docker/prusti
--- a/docker/prusti
+++ b/docker/prusti
@@ -1,7 +1,11 @@
 #!/bin/bash
 
+info() { echo -e "[-] ${*}"; }
+error() { echo -e "[!] ${*}"; }
+
 # Get the directory in which this script is contained
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
+info "Executing Prusti script located in '$DIR'"
 
 # Read and set some environment variables
 export JAVA_HOME=${JAVA_HOME:-"/usr/lib/jvm/default-java"}
@@ -10,48 +14,84 @@ export RUST_LOG=${RUST_LOG:-info}
 # The compiler version for which Prusti has been compiled
 RUST_VERSION=nightly-2018-06-27-x86_64-unknown-linux-gnu
 
-# Build the COMPILER_PATH path
-COMPILER_PATH=/usr/local/rustup/toolchains/${RUST_VERSION}
+# Check JAVA_HOME
+if [ ! -d "$JAVA_HOME" ]; then
+	error "Unable to find JAVA_HOME."
+	error "It looks like the JAVA_HOME environment variable has not been set."
+	exit 1
+fi
+
+# Set COMPILER_PATH
+if [ -d "/usr/local/rustup/toolchains/${RUST_VERSION}" ]; then
+	COMPILER_PATH="/usr/local/rustup/toolchains/${RUST_VERSION}"
+fi
 if [ -d "$HOME/.rustup/toolchains/${RUST_VERSION}" ]; then
 	COMPILER_PATH="$HOME/.rustup/toolchains/${RUST_VERSION}"
 fi
 if [ -d "$RUSTUP_HOME/toolchains/${RUST_VERSION}" ]; then
 	COMPILER_PATH="$RUSTUP_HOME/.rustup/toolchains/${RUST_VERSION}"
 fi
-echo "Using COMPILER_PATH '$COMPILER_PATH'"
+if [ -z "$COMPILER_PATH" ]; then
+	error "Unable to find COMPILER_PATH."
+	error "It looks like the Rust compiler version '${RUST_VERSION}' has not been installed with the rustup tool."
+	exit 1
+else
+	info "Using COMPILER_PATH '$COMPILER_PATH'"
+fi
 
-# Build the PRUSTI_HOME path
-PRUSTI_HOME=/usr/local/prusti
+# Set PRUSTI_DRIVER
+if [ -x "/usr/local/prusti/prusti-driver" ]; then
+	PRUSTI_DRIVER="/usr/local/prusti/prusti-driver"
+fi
 if [ -x "$DIR/../target/debug/prusti-driver" ]; then
-	PRUSTI_HOME="$DIR/../target/debug"
+	[[ "$DIR/../target/debug/prusti-driver" -nt "$PRUSTI_DRIVER" ]] && PRUSTI_DRIVER="$DIR/../target/debug/prusti-driver"
 fi
 if [ -x "$DIR/../target/release/prusti-driver" ]; then
-	PRUSTI_HOME="$DIR/../target/release"
+	[[ "$DIR/../target/release/prusti-driver" -nt "$PRUSTI_DRIVER" ]] && PRUSTI_DRIVER="$DIR/../target/release/prusti-driver"
 fi
-echo "Using PRUSTI_HOME '$PRUSTI_HOME'"
+if [ -z "$PRUSTI_DRIVER" ]; then
+	error "Unable to find PRUSTI_DRIVER."
+	error "It looks like Prusti has not been compiled or installed properly."
+	exit 1
+else
+    info "Using PRUSTI_DRIVER '$PRUSTI_DRIVER'"
+fi
 
-# Build the PRUSTI_CONTRACTS_LIB path
-for file in "${PRUSTI_HOME}"/deps/libprusti_contracts-*.rlib; do
-	[[ $file -nt $PRUSTI_CONTRACTS_LIB ]] && PRUSTI_CONTRACTS_LIB=$file
-done
+# Set PRUSTI_HOME
+PRUSTI_HOME="$(dirname "$PRUSTI_DRIVER")"
+info "Using PRUSTI_HOME '$PRUSTI_HOME'"
+
+# Set PRUSTI_CONTRACTS_LIB
 if [ -x "${PRUSTI_HOME}/libprusti_contracts.rlib" ]; then
 	PRUSTI_CONTRACTS_LIB="${PRUSTI_HOME}/libprusti_contracts.rlib"
 fi
-echo "Using PRUSTI_CONTRACTS_LIB '$PRUSTI_CONTRACTS_LIB'"
+for file in "${PRUSTI_HOME}"/deps/libprusti_contracts-*.rlib; do
+	[[ "$file" -nt "$PRUSTI_CONTRACTS_LIB" ]] && PRUSTI_CONTRACTS_LIB="$file"
+done
+if [ -z "$PRUSTI_CONTRACTS_LIB" ]; then
+	error "Unable to find PRUSTI_CONTRACTS_LIB."
+	error "It looks like Prusti has not been compiled or installed."
+	exit 1
+else
+    info "Using PRUSTI_CONTRACTS_LIB '$PRUSTI_CONTRACTS_LIB'"
+fi
 
-# Build the PRUSTI_DRIVER path
-PRUSTI_DRIVER=${PRUSTI_HOME}/prusti-driver
-echo "Using PRUSTI_DRIVER '$PRUSTI_DRIVER'"
-
-# Build the JAVA_LIBJVM_DIR path
+# Set JAVA_LIBJVM_DIR
 JAVA_LIBJVM_DIR="$(dirname "$(find "$(readlink -f "$JAVA_HOME")" -name "libjvm.so")")"
-echo "Using JAVA_LIBJVM_DIR '$JAVA_LIBJVM_DIR'"
+if [ ! -f "$JAVA_LIBJVM_DIR/libjvm.so" ]; then
+	error "Unable to find JAVA_LIBJVM_DIR."
+	error "It looks like the Java JRE has not been installed."
+	exit 1
+else
+    info "Using JAVA_LIBJVM_DIR '$JAVA_LIBJVM_DIR'"
+fi
 
 export LD_LIBRARY_PATH=${COMPILER_PATH}/lib:${JAVA_LIBJVM_DIR}:${PRUSTI_HOME}:${PRUSTI_HOME}/deps
-echo "Using LD_LIBRARY_PATH '$LD_LIBRARY_PATH'"
+info "Using LD_LIBRARY_PATH '$LD_LIBRARY_PATH'"
 
 # Run Prusti
-${PRUSTI_DRIVER} \
+info "Run Prusti...\n"
+exec ${PRUSTI_DRIVER} \
 	-L ${COMPILER_PATH}/lib/rustlib/x86_64-unknown-linux-gnu/lib/ \
 	--extern prusti_contracts="${PRUSTI_CONTRACTS_LIB}" \
 	$@
